version: '3'
services:
  db:
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: bin/rails server --port 4000 --binding 0.0.0.0
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      PG_PASSWORD: password
    volumes:
      - .:/myapp